### PR TITLE
Update test_SST1DBLoader.py by testing scan ID 87758

### PR DESCRIPTION
**Pull request by PriyankaKetkarBNL**
Added a set of tests for scan ID 87758 to check that the loadRun function continues to work for a more recent scan and that it works for a case in which a single energy and two polarizations are run.

See issue 154 for more details.

### CODE REVIEW

**Comment by pbeaucage** [comment]
@PriyankaKetkarBNL if you look in the CI logs you'll see that the new test is failing.  This might be as simple as a problem with two tests having the same name - can you try changing that and see if it passes?

**Comment by PriyankaKetkarBNL** [comment]
I just updated the test names.  It seems like some of the checks are succeeding now, but still others are failing.  I don't immediately follow where the issue is.

**Comment by pbeaucage** [comment]
The tests weren't running due to an old version merged in #132.  The ones marked as succeeded were documentation and security analysis; the tests are in "PyHyperScattering CI Testing".  I updated with main and tests should run again now.

**Review by pbeaucage — APPROVED** [review]
LGTM, tests pass, OK to merge if name changes are ok.

**Pull request merged**
