### PR TITLE
Cyrsoxs dev

### PR DESCRIPTION
**Pull request by pdudenas**
cyrsoxsLoader and WPintegrator have been updated for CyRSoXS 1.1.4.0.0.0. Ready to merge with main.

### CODE REVIEW

**Comment by pdudenas** [comment]
Failed tests are from test_11012Loader and test_SST1Loader on Python 3.8. All tests for cyrsoxsLoader and WPintegrator pass.

**Comment by pbeaucage** [comment]
Is this a pinned version at 1.1.4.0.0.0, or is there backward compatibility?

Probably doesn't matter at this stage (given that we control all the copies of cyrsoxs in existence), but it would be good to have it be backward compatible as much as possible.

Actually, I guess given that the tests pass, it must be backward compatible, eh?

**Review by pbeaucage — APPROVED** [review]
LGTM, only comment is that it would be good to document how far back in cyrsoxs output this supports.

**Comment by pbeaucage** [comment]
Actually, hiding behind my failure to fix the test written up in #43 was a test failure on Windows.  Looks like the file path in the cyrsoxs loader gets mangled?

**Comment by pbeaucage** [comment]
My best guess is that it's https://github.com/usnistgov/PyHyperScattering/blob/66f278311e205b4f5e7578593940e36b11e6d98a/src/PyHyperScattering/cyrsoxsLoader.py#L99 here

does glob work on Windows?

**Comment by pdudenas** [comment]
@pbeaucage I believe the loader is backward compatible with all versions with this try, except block

https://github.com/usnistgov/PyHyperScattering/blob/518d369287397131dbba7087d337b667fec9d5fc/src/PyHyperScattering/cyrsoxsLoader.py#L131-L134

**Pull request merged**
